package finki.ukim.backend.request_management.model.enums;

public enum LogAction {
    REQUEST_CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ROUTING_CONFIRMED,
    ROUTING_REJECTED,
    CATEGORY_CHANGED,
    DEPARTMENT_CHANGED,
    EMPLOYEE_ASSIGNED,
    EMPLOYEE_REMOVED,
    COMMENT_ADDED,
    FILE_UPLOADED,
    FILE_REMOVED,
    REQUEST_RESOLVED,
    REQUEST_REJECTED,
    REQUEST_CANCELED,


//    - REQUEST_CREATED
//- REQUEST_UPDATED
//- STATUS_CHANGED
//- ROUTING_CONFIRMED
//- ROUTING_REJECTED
//- ROUTING_REOPENED
//- DEPARTMENT_CHANGED
//- CATEGORY_CHANGED
//- PRIORITY_CHANGED
//- AI_SUGGESTION_CREATED
//- AI_SUGGESTION_APPROVED
//- AI_SUGGESTION_REJECTED
//- EMPLOYEE_ASSIGNED
//- EMPLOYEE_REMOVED
//- COMMENT_ADDED
//- FILE_UPLOADED
}
