package finki.ukim.backend.request_management.model.enums;

public enum LogAction {
    REQUEST_CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ROUTING_CONFIRMED,
    ROUTING_REJECTED,
    ROUTING_REOPENED,
    CATEGORY_CHANGED,
    DEPARTMENT_CHANGED,
    EMPLOYEE_ASSIGNED,
    EMPLOYEE_REMOVED,
    COMMENT_ADDED,
    COMMENT_DELETED,
    COMMENT_EDITED,
    FILE_UPLOADED,
    FILE_REMOVED,
    REQUEST_RESOLVED,
    REQUEST_REJECTED,
    REQUEST_CANCELED,
    AI_SUGGESTION_CREATED,
    AI_SUGGESTION_FAILED,
    AI_SUGGESTION_APPROVED,
    AI_SUGGESTION_REJECTED
}
