-- =========================
-- Departments
-- =========================

INSERT INTO departments (name, description)
VALUES
    ('Roads and Infrastructure', 'Responsible for roads, sidewalks, potholes, traffic signs, bridges, and public infrastructure.'),
    ('Public Lighting', 'Responsible for street lights, lighting poles, damaged lamps, and public lighting maintenance.'),
    ('Waste Management', 'Responsible for waste collection, illegal dumping, bins, containers, and public cleanliness.'),
    ('Water and Sewage', 'Responsible for water leaks, sewage problems, drainage, manholes, and stormwater systems.'),
    ('Parks and Green Areas', 'Responsible for parks, trees, grass areas, playgrounds, and public green spaces.'),
    ('Public Safety', 'Responsible for safety-related public issues and emergency municipal coordination.'),

    ('Traffic and Mobility', 'Responsible for traffic flow, pedestrian crossings, road markings, traffic lights, and mobility improvements.'),
    ('Urban Planning', 'Responsible for urban development, zoning, construction planning, and public space organization.'),
    ('Building Inspection', 'Responsible for inspection of buildings, unsafe structures, illegal construction, and construction complaints.'),
    ('Environmental Protection', 'Responsible for pollution reports, environmental hazards, air quality, and ecological protection.'),
    ('Noise Control', 'Responsible for public noise complaints, loud activities, and noise regulation enforcement.'),
    ('Public Transport', 'Responsible for bus stops, public transport infrastructure, transport complaints, and route-related issues.'),
    ('Parking Services', 'Responsible for parking zones, damaged parking signs, illegal parking areas, and parking infrastructure.'),
    ('Road Signage', 'Responsible for damaged, missing, or unclear traffic signs and public road signalization.'),
    ('Sidewalk Maintenance', 'Responsible for damaged sidewalks, pedestrian paths, curbs, and walking area accessibility.'),
    ('Bridge Maintenance', 'Responsible for bridges, overpasses, underpasses, and structural road infrastructure issues.'),

    ('Stormwater Drainage', 'Responsible for rainwater drainage, blocked drains, flooded streets, and stormwater channels.'),
    ('Public Toilets', 'Responsible for public toilet maintenance, cleanliness, repairs, and accessibility.'),
    ('Street Cleaning', 'Responsible for street sweeping, public area cleaning, litter removal, and cleanliness complaints.'),
    ('Recycling Services', 'Responsible for recycling bins, recycling collection, and recycling-related public requests.'),
    ('Illegal Dumping Control', 'Responsible for reports of illegal waste disposal and cleanup coordination.'),
    ('Hazardous Waste', 'Responsible for hazardous waste reports, unsafe materials, and proper disposal coordination.'),
    ('Animal Control', 'Responsible for stray animals, animal-related public safety issues, and animal welfare coordination.'),
    ('Veterinary Coordination', 'Responsible for municipal veterinary issues, animal shelters, and animal health coordination.'),
    ('Public Markets', 'Responsible for market areas, vendor spaces, cleanliness, and public market maintenance.'),
    ('Cemetery Services', 'Responsible for cemetery maintenance, access roads, lighting, and public cemetery infrastructure.'),

    ('Schools and Education Facilities', 'Responsible for municipal school facility issues, repairs, safety, and infrastructure maintenance.'),
    ('Kindergartens', 'Responsible for kindergarten buildings, playgrounds, safety issues, and maintenance requests.'),
    ('Sports Facilities', 'Responsible for sports halls, fields, courts, public exercise areas, and sports infrastructure.'),
    ('Cultural Facilities', 'Responsible for cultural centers, libraries, public halls, and cultural infrastructure maintenance.'),
    ('Youth and Community Centers', 'Responsible for youth centers, community spaces, and related municipal facilities.'),
    ('Social Services', 'Responsible for municipal social support facilities and citizen assistance coordination.'),
    ('Healthcare Facilities Coordination', 'Responsible for municipal healthcare-related infrastructure and facility coordination.'),
    ('Accessibility Services', 'Responsible for ramps, accessible sidewalks, public access barriers, and disability-friendly infrastructure.'),
    ('Public Buildings Maintenance', 'Responsible for maintenance and repair of municipal public buildings.'),
    ('Municipal Property Management', 'Responsible for municipal-owned land, buildings, and property-related issues.'),

    ('Fire Safety Coordination', 'Responsible for fire safety access, hydrants, emergency routes, and coordination with fire services.'),
    ('Emergency Management', 'Responsible for emergency preparedness, crisis coordination, and urgent municipal response support.'),
    ('Disaster Risk Reduction', 'Responsible for flood, landslide, storm, earthquake, and disaster prevention coordination.'),
    ('Winter Maintenance', 'Responsible for snow removal, icy roads, salt spreading, and winter road safety.'),
    ('Flood Protection', 'Responsible for flood prevention infrastructure, flood reports, and water overflow coordination.'),
    ('Landslide Monitoring', 'Responsible for unstable land, landslide risks, and slope safety reports.'),
    ('Public Health and Sanitation', 'Responsible for sanitation issues, public hygiene, pest control, and health-related municipal concerns.'),
    ('Pest Control', 'Responsible for insects, rodents, mosquito control, and pest-related public complaints.'),
    ('Food Safety Coordination', 'Responsible for coordination of food safety concerns in public markets and municipal spaces.'),
    ('Air Quality Monitoring', 'Responsible for air pollution reports, monitoring coordination, and environmental quality concerns.'),

    ('Energy Efficiency', 'Responsible for energy-saving measures in public buildings and municipal energy projects.'),
    ('Smart City Systems', 'Responsible for digital city systems, sensors, smart infrastructure, and technology-based services.'),
    ('IT and Digital Services', 'Responsible for municipal digital platforms, citizen service portals, and technical support.'),
    ('Citizen Support Center', 'Responsible for citizen communication, service request support, and public information assistance.'),
    ('Complaints and Appeals', 'Responsible for citizen complaints, appeals, follow-ups, and administrative coordination.'),
    ('Permits and Licensing', 'Responsible for municipal permits, licenses, approvals, and related citizen requests.'),
    ('Legal Affairs', 'Responsible for legal coordination, municipal regulations, and legal case support.'),
    ('Finance and Budgeting', 'Responsible for municipal budget issues, payments, public financial requests, and fee coordination.'),
    ('Procurement', 'Responsible for public procurement, municipal contracts, and supplier coordination.'),
    ('Human Resources', 'Responsible for municipal staff administration, internal staffing, and employee-related processes.'),

    ('Tourism and Local Development', 'Responsible for tourism infrastructure, local promotion, and development-related initiatives.'),
    ('Economic Development', 'Responsible for business support, investment coordination, and local economic development.'),
    ('Agriculture and Rural Development', 'Responsible for rural infrastructure, agricultural support, and village development issues.'),
    ('Forestry and Natural Resources', 'Responsible for forests, natural areas, resource protection, and related public concerns.'),
    ('River and Canal Maintenance', 'Responsible for rivers, canals, embankments, and watercourse maintenance.'),
    ('Public Fountains', 'Responsible for public fountains, drinking water points, and fountain maintenance.'),
    ('Monuments and Memorials', 'Responsible for monuments, memorial sites, public statues, and heritage-related maintenance.'),
    ('Street Furniture', 'Responsible for benches, bus shelters, barriers, public signs, and other street furniture.'),
    ('Playground Maintenance', 'Responsible for children playgrounds, damaged equipment, safety surfaces, and playground repairs.'),
    ('Tree Maintenance', 'Responsible for tree pruning, fallen branches, dangerous trees, and urban tree care.'),

    ('Grass and Landscaping', 'Responsible for mowing, landscaping, public flower areas, and green surface maintenance.'),
    ('Public Events Coordination', 'Responsible for public event infrastructure, temporary closures, and municipal event support.'),
    ('Security Cameras and Monitoring', 'Responsible for public surveillance infrastructure, damaged cameras, and monitoring coordination.'),
    ('Graffiti Removal', 'Responsible for graffiti reports, wall cleaning, and public surface restoration.'),
    ('Vandalism Repair', 'Responsible for damaged public property caused by vandalism and repair coordination.'),
    ('Public Information and Signboards', 'Responsible for public notice boards, municipal signs, information panels, and announcements.'),
    ('Municipal Inspection', 'Responsible for general municipal inspection, field checks, and enforcement coordination.'),
    ('Department Coordination', 'Responsible for interdepartmental routing, request reassignment, and coordination between municipal units.');

-- =========================
-- Municipalities
-- =========================

INSERT INTO municipalities (name, code)
VALUES ('Kumanovo', 'KUM'),
       ('Skopje', 'SKP'),
       ('Tetovo', 'TET'),
       ('Bitola', 'BTL'),
       ('Ohrid', 'OHR'),
       ('Prilep', 'PRL'),
       ('Gostivar', 'GTV'),
       ('Struga', 'STR');


-- =========================
-- Categories
-- =========================

INSERT INTO categories (name, description, department_id)
VALUES ('Pothole',
        'Reports related to potholes or damaged road surfaces.',
        (SELECT id FROM departments WHERE name = 'Roads and Infrastructure')),
       ('Damaged Sidewalk',
        'Reports related to broken, blocked, or unsafe sidewalks.',
        (SELECT id FROM departments WHERE name = 'Roads and Infrastructure')),
       ('Damaged Traffic Sign',
        'Reports related to missing, broken, or incorrectly placed traffic signs.',
        (SELECT id FROM departments WHERE name = 'Roads and Infrastructure')),
       ('Broken Street Light',
        'Reports related to non-working or damaged public street lights.',
        (SELECT id FROM departments WHERE name = 'Public Lighting')),
       ('Damaged Lighting Pole',
        'Reports related to damaged or unsafe lighting poles.',
        (SELECT id FROM departments WHERE name = 'Public Lighting')),
       ('Overflowing Trash Bin',
        'Reports related to full or overflowing public trash bins.',
        (SELECT id FROM departments WHERE name = 'Waste Management')),
       ('Illegal Dumping',
        'Reports related to waste dumped in unauthorized public areas.',
        (SELECT id FROM departments WHERE name = 'Waste Management')),
       ('Water Leak',
        'Reports related to visible water leaks in public areas.',
        (SELECT id FROM departments WHERE name = 'Water and Sewage')),
       ('Blocked Drain',
        'Reports related to blocked storm drains or drainage problems.',
        (SELECT id FROM departments WHERE name = 'Water and Sewage')),
       ('Open or Damaged Manhole',
        'Reports related to missing, open, or damaged manhole covers.',
        (SELECT id FROM departments WHERE name = 'Water and Sewage')),
       ('Damaged Playground Equipment',
        'Reports related to broken or unsafe playground equipment.',
        (SELECT id FROM departments WHERE name = 'Parks and Green Areas')),
       ('Fallen Tree or Branch',
        'Reports related to fallen trees, dangerous branches, or tree maintenance.',
        (SELECT id FROM departments WHERE name = 'Parks and Green Areas')),
       ('Damaged Public Bench',
        'Reports related to broken benches or public seating areas.',
        (SELECT id FROM departments WHERE name = 'Parks and Green Areas')),
       ('Unsafe Public Area',
        'Reports related to safety risks in public spaces.',
        (SELECT id FROM departments WHERE name = 'Public Safety'));