spring.application.name=backend

#### OPEN API ###
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#### LOGGING ###
logging.level.root=INFO
logging.level.finki.ukim.backend=DEBUG
logging.level.org.springframework=WARN

logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

#### JWT AUTH ###
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer

#### Resend Email API ####
resend.api-key=${RESEND_KEY}
resend.from-email=${RESEND_FROM_EMAIL}

### Password reset url ###
auth.password-reset.base-url=http://localhost:3000/reset-password

#### ACTIVE PROFILE ###
spring.profiles.active=dev
